[config]
reload_apps = false

[templates.ghostty]
input_path  = "~/.config/matugen/templates/ghostty.conf.mustache"
output_path = "~/.config/matugen/generated/ghostty-colors.conf"

[templates.zsh-highlight]
input_path  = "~/.config/matugen/templates/zsh-highlight.zsh.mustache"
output_path = "~/.config/matugen/generated/zsh-highlight.zsh"

[templates.zsh-fzf]
input_path  = "~/.config/matugen/templates/zsh-fzf-colors.zsh.mustache"
output_path = "~/.config/matugen/generated/zsh-fzf-colors.zsh"

[templates.hyprlock]
input_path  = "~/.config/matugen/templates/hyprlock.conf.mustache"
output_path = "~/.config/matugen/generated/hyprlock-colors.conf"

[templates.eza]
input_path  = "~/.config/matugen/templates/eza.yml.mustache"
output_path = "~/.config/matugen/generated/eza/theme.yml"

[templates.starship]
input_path  = "~/.config/matugen/templates/starship.toml.mustache"
output_path = "~/.config/matugen/generated/starship/starship.toml"

[templates.bat]
input_path  = "~/.config/matugen/templates/bat.tmTheme.mustache"
output_path = "~/.config/bat/themes/matugen.tmTheme"

[templates.hyprland-lua]
input_path  = "~/.config/matugen/templates/colors.lua.mustache"
output_path = "~/.config/hypr/generated/colors.lua"
