[config]
reload_apps = false

[templates.hyprland]
input_path  = "~/.config/matugen/templates/hyprland.conf.mustache"
output_path = "~/.config/matugen/generated/hyprland-colors.conf"

[templates.ghostty]
input_path  = "~/.config/matugen/templates/ghostty.conf.mustache"
output_path = "~/.config/matugen/generated/ghostty-colors.conf"

[templates.rofi]
input_path  = "~/.config/matugen/templates/rofi.rasi.mustache"
output_path = "~/.config/matugen/generated/rofi-colors.rasi"

[templates.quickshell]
input_path  = "~/.config/matugen/templates/quickshell-colors.json.mustache"
output_path = "/tmp/qs_colors.json"

[templates.zsh-highlight]
input_path  = "~/.config/matugen/templates/zsh-highlight.zsh.mustache"
output_path = "~/.config/matugen/generated/zsh-highlight.zsh"

[templates.zsh-fzf]
input_path  = "~/.config/matugen/templates/zsh-fzf-colors.zsh.mustache"
output_path = "~/.config/matugen/generated/zsh-fzf-colors.zsh"

[templates.hyprlock]
input_path  = "~/.config/matugen/templates/hyprlock.conf.mustache"
output_path = "~/.config/matugen/generated/hyprlock-colors.conf"

[templates.eza]
input_path  = "~/.config/matugen/templates/eza.yml.mustache"
output_path = "~/.config/eza/theme.yml"

[templates.starship]
input_path  = "~/.config/matugen/templates/starship.toml.mustache"
output_path = "~/.config/starship.toml"
