# ███╗   ███╗██╗███████╗ ██████╗
# ████╗ ████║██║██╔════╝██╔════╝
# ██╔████╔██║██║███████╗██║     
# ██║╚██╔╝██║██║╚════██║██║     
# ██║ ╚═╝ ██║██║███████║╚██████╗
# ╚═╝     ╚═╝╚═╝╚══════╝ ╚═════╝
#-------------------------------


misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    
    mouse_move_enables_dpms = true      # Screen wakes on mouse move
    key_press_enables_dpms = true       # Screen wakes on key press
    #render_ahead_of_time = false         # Performance setting
    #render_ahead_safeguard = 5
    allow_session_lock_restore = true    # Restore after lock screen
}
