# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗██████╗ ██╗   ██╗██╗     ███████╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔══██╗██║   ██║██║     ██╔════╝
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██████╔╝██║   ██║██║     █████╗  
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██╔══██╗██║   ██║██║     ██╔══╝  
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║  ██║╚██████╔╝███████╗███████╗
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝
#------------------------------------------------------------------------------------


# Rule + match 
windowrule = no_blur on, match:class brave-browser
windowrule = fullscreen on, match:class steam_app_.*

# Steam
windowrule = float on, match:class ^(Steam)$, match:title negative:^(Steam)$

# Floating apps
windowrule = float on, match:class ^(pavucontrol|blueman-manager|nm-connection-editor|gnome-calculator|qalculate-gtk)$
windowrule = float on, match:class ^(Lxappearance|qt5ct|qt6ct|kvantummanager|org.kde.systemsettings)$
windowrule = float on, match:class ^(feh|imv|sxiv|mpv)$
windowrule = float on, match:class ^(thunar|pcmanfm|nemo| Dolphin)$