#:schema https://yazi-rs.github.io/schemas/keymap.json
[mgr]
prepend_keymap = [
    { on = "<Esc>",     run = "escape --all",            desc = "Cancel modes and clear selection" },
    { on = "e",         run = "open --interactive",      desc = "Open with..." },
    { on = "!",         run = "shell --block --interactive", desc = "Run a blocking shell command" },
    { on = [ "c", "m" ], run = "plugin chmod",           desc = "Change permissions" },
]
