# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗██████╗ ██╗   ██╗██╗     ███████╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔══██╗██║   ██║██║     ██╔════╝
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██████╔╝██║   ██║██║     █████╗  
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██╔══██╗██║   ██║██║     ██╔══╝  
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║  ██║╚██████╔╝███████╗███████╗
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝
#------------------------------------------------------------------------------------


# Rule + match 
windowrule = no_blur on, match:class brave-browser
windowrule = fullscreen on, match:class steam_app_.*

# Floating apps
windowrule = float on, match:class ^(pavucontrol|blueman-manager|nm-connection-editor|gnome-calculator|qalculate-gtk)$,
windowrule = float on, match:class ^(Lxappearance|qt5ct|qt6ct|kvantummanager|org.kde.systemsettings)$,
windowrule = float on, match:class ^(feh|imv|sxiv|mpv)$

# Applications
windowrule = float on, size 1600 900, move onscreen center, match:class ^(Bitwarden)$,
windowrule = float on, match:class ^(Steam)$, match:title negative:^(Steam)$
